describe('Homepage', () => {
  it('visit homepage', () => {
    cy.viewport(1280, 720)
    cy.visit('https://stripe.com/en-us')
    cy.get('[data-js-target="CookieSettingsNotificationRejectAll.rejectAllButton"]').click()
    cy.wait(1000)
    cy.get('a[data-analytics-label="Developer docs CTA"]').as('btnDocs')
    cy.get('@btnDocs').scrollIntoView()
    cy.wait(1000)
    cy.get('@btnDocs').trigger('mouseover')
    cy.wait(1000)
    cy.get('@btnDocs').click()
    cy.wait(1000)
    cy.get('a[href="/docs/payments?payments=popular"]').as('btnPayments')
    cy.get('@btnPayments').click()
    cy.wait(1000)
    cy.get('h2#more-guides').as('h2')
    cy.get('@h2').scrollIntoView()
    cy.get('@h2').should('have.text', 'More guides')
  })
})
